# Созданеи, чтение и запись данныхи

In [1]:
import pandas as pd
import numpy as np

### DataFrame() Двумерный массив данных
DataFrame() - это класс который создаёт двумерные таблицы (строки и колонки) по оси 0 и оси 1. Основной объект Pandas.

Берётся класс из библиотеки pd
DataFrame обычно называют df

pd.DataFrame(data, index, columns, dtype, copy) = Парматеры класса
- data	Данные (словарь, список, массив)	{'A': [1, 2], 'B': [3, 4]}
- index	Метки строк	['row1', 'row2']
- columns	Названия колонок	['A', 'B']
- dtype	это принудительная конвертация данных в нужный тип. 
- copy	Копировать данные?	True / False

Параметр data:
Класс принимает 3 типы данных:
- Словарь
- Список
- NumPy масссив

#### date = dict

In [2]:
# Словарь со сколярным значениями
# В словарях указывать пармерт columns не нужно указывать так как у нас ключи это колонки
# В словарях обычно не указывают явный тип данных через dtype так как у нас в разных колонках разные типы данных

df = pd.DataFrame({
    'name': 'Umed', # Одно значений (сколярное значение)
    'age': 22,      # Одно значений (сколярное значение) 
},  index=['0'])     # Без index pandas не знает, как назвать единственную строку.
                    # Названием колонок становяться ключи словаря 
df

   name  age
0  Umed   22

In [3]:
# Словарь со значениями список
# В словарях указывать пармерт columns не нужно указывать так как у нас ключи это колонки
# В словарях обычно не указывают явный тип данных через dtype так как у нас в разных колонках разные типы данных
df2 = pd.DataFrame({
    'name': ['UMED', 'Numon'], # Если значене ключа у нас список из N значений то у нас инедксы (index) строк исоздаются сами  
    'age': [20, 25]            # Если значене ключа у нас список из N значений то у нас инедксы (index) строк исоздаются сами
})                             # Названием колонок становяться ключи словаря
df2

    name  age
0   UMED   20
1  Numon   25

In [4]:
# Данные редко указывают внутри класса, 
# обычно их присваивают перменным а потом передают в качестве значений параметров

# Задаём переменные 
names = ['Umed', 'Numon', 'Ali', 'Numon']
ages = [20, 30, 18, 22]

# Присваиваем перменные в качестве занченйи ключей нашего словаря
df = pd.DataFrame({
    'names': names,
    'ages': ages,
})
df

   names  ages
0   Umed    20
1  Numon    30
2    Ali    18
3  Numon    22

#### date = list

В списках принято явно указывать названия колонок через параметр columns

In [5]:
# Данные в виде списков
# В списках принято явно указывать названия колонок через параметр columns
df3 = pd.DataFrame([1,2,3], 
                   columns=['A'], # В списках принято явно указывать названия колонок через параметр columns
                   dtype=float)   #dtype — это принудительная конвертация данных в нужный тип. 
df3

     A
0  1.0
1  2.0
2  3.0

In [6]:
# Данные в виде списка списков
# В списках принято явно указывать названия колонок через параметр columns
df3 = pd.DataFrame([[1,2,3],
                    [1,2,3]], 
                   columns=['A','B','C']) # В списках принято явно указывать названия колонок через параметр columns
df3
# Две строки по оси 0 
# Три колонки по оси 1

   A  B  C
0  1  2  3
1  1  2  3

In [7]:
# Данные в виде списков словарей
df4 = pd.DataFrame([
    {'name': 'Alex', 'age':25},
    {'name': 'Maria', 'age': 30},
])
df4

    name  age
0   Alex   25
1  Maria   30

In [8]:
# В случаи списков тоже принято значение параметров указыват вне класса в виде переменной, 
# а потом передаывать в качестве значений парарметров

# Задаём перменные 
num = [1,2,3]
col = ['A']

# Передаём перменные в качестве значенйи парметров
df = pd.DataFrame(num, columns=col)
df

   A
0  1
1  2
2  3

### Series()
Series — это класс, который создаёт одномерный массив с индексом. Как один столбец таблицы.

Берётся класс из библиотеки pd

pd.Series(data, index, dtype, name, copy)

- data	Данные	[1, 2, 3]
- index	Метки	['a', 'b', 'c'] Присваиваем инидексы явно через парметр index
- dtype	Тип данных	= int64 это принудительная конвертация данных в нужный тип. 
- name	Имя Series	'my_series'
- copy	Копировать?	True / False

In [9]:
# Создаём одну колонку класс Series()
# Явна присваивать индексы не тнеобходимости 
df = pd.Series([10, 20, 30])
df

0    10
1    20
2    30
dtype: int64

In [10]:
# Также мы можем явно указывать значения индексов
df = pd.Series([1,2,3], 
               index=['a','b','c'] # Явна Присваиваем инедксы в виде букв
              )
df

a    1
b    2
c    3
dtype: int64

In [11]:
# Указываем индексы класса в виде словаря, где ключь у нас индекс а значение его это цифра
# Ключь это индекс, 
# Значение ключа это значение колонки 

df = pd.Series({'a': 1, 'b':2, 'c':3}) 
df

a    1
b    2
c    3
dtype: int64

In [12]:
# Можно также явна укзаать имя Series()
df = pd.Series(
    [10,10,10],
    index=['a','b','c'],
    name='value', # Указываем на имя Series
)
df

a    10
b    10
c    10
Name: value, dtype: int64

In [13]:
# Также монжо сразу явно конвертировать типы данных Serie
df = pd.Series(
    [10,10,10],
    index=['a','b','c'],
    name='value', 
    dtype=float, # Явна меняем тип данных 
)
df

a    10.0
b    10.0
c    10.0
Name: value, dtype: float64

In [14]:
# В Serias также можн передавать перменные в качесве аргументов параметров

# Создаём перменную которую передадим в класс Serias
num01 = [10,11,12]

df = pd.Series(num01) # Передаём в качестве параметра в парметр data перменную содержащую массив данных
df

0    10
1    11
2    12
dtype: int64

## Чтения разных типов файлов 
pd.read_*() — читает файл → DataFrame.

Методы
- read_csv() -- Читает CSV-файл (текстовый файл с разделителями) → DataFrame.
- read_excel() -- Читает excel-файл → DataFrame.

Докончить

### read_csv() = чтение csv файла. 
pd.read_csv(filepath, sep, header, names, index_col, usecols, dtype, encoding, ...)
Основные параметры
Параметр	 Что означает	Пример
- filepath  - Путь к файлу	- 'data.csv'
- sep	    - Разделитель	- ',', ';', '\t'
- header    - Строка с заголовками	- 0 (первая)
- names	    - Свои названия колонок	- ['A', 'B']
- index_col - Колонка-индекс	    - 'id'
- usecols	- Какие колонки читать	- ['A', 'B']
- dtype	    - Типы данных	        - {'A': int}
- encoding	- Кодировка	            - 'utf-8'
- nrows	    - Сколько строк читать	- 100
- skiprows	- Пропустить строк	    - 5
- na_values	- Что считать NaN	    - ['NA', '']

In [15]:
# Читаем по абсолютному пути
# Cчитает первую строку файла заголовком (header), а не данными.
df = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'E:/python/notebooks/Pandas/sandb.csv'

In [ ]:
# Читаем по названию файла, 
# через такой метод мы можем считать только те файлы которые находяться в той директории
# с которой работаем 
# Cчитает первую строку файла заголовком (header), а не данными.
df = pd.read_csv('sandb.csv')
df.head()
# read_csv() читает файл с первой строки, но первую строку по умолчанию использует как заголовок, а не как данные.
#  Реальные данные начинаются со второй строки файла (если header не отключён).

In [ ]:
# header  = указываем строку которая становится загаловком в DataFrame, всё что после этой строки это данные 
# nrows = указываем сколько строк читать 
df  = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv',
                  header=3, # заголовок на 3-й строке (0,1,2 → 2-я), по умолчанию она 0 
                  nrows=10) # Сколько строк считывать после загаловка 
df

In [ ]:
# index_col = «возьми вот эту колонку и сделай её индексом (подписями строк) вместо стандартных 0, 1, 2, 3...».
df  = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv',
                  header=3, # заголовок на 3-й строке (0,1,2 → 2-я), по умолчанию она 0 
                  nrows=10, # Сколько строк считывать после загаловка 
                  index_col='fpd_01_shis')
df

In [ ]:
# usecols = Говорит pandas: читай только эти колонки, остальные игнорируй (даже не загружай их в память).
df  = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv',
                  header=3, # заголовок на 3-й строке (0,1,2 → 2-я), по умолчанию она 0
                  nrows=10, # Сколько строк считывать после загаловка 
                  usecols=['fpd_01_shis', 'cum_znam_01']) # Отбирает толкь оте колонки которые указать 
df

In [ ]:
# dtype = мы говорим pandas, каким типом читать колонку с самого начала, а не меняем тип уже после загрузки.
# names = names заменяет заголовок, но при этом первая строка файла остаётся как данные 
# usecols = Говорит pandas: читай только эти колонки, остальные игнорируй (даже не загружай их в память).
df  = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv',
                  header=0, # заголовок на 3-й строке (0,1,2 → 2-я), по умолчанию она 0
                  nrows=10, # Сколько строк считывать после загаловка 
                  names=['A','B'],   # names заменяет заголовок, но при этом первая строка файла остаётся как данные 
                  dtype={'A':str})   # Колонку которая имеет заголовок A читает как str 
df

In [ ]:
# skiprows — пропустить строки сверху
# Говорит pandas: не читай первые N строк файла, начни сразу с нужной.
# С skiprows=5 первые 5 строк (весь «мусор» сверху) пропускаются, и pandas начинает читать

df  = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv',
                  header=0, # заголовок на 3-й строке (0,1,2 → 2-я), по умолчанию она 0
                  nrows=10, # Сколько строк считывать после загаловка 
                  names=['A','B'],   # names заменяет заголовок, но при этом первая строка файла остаётся как данные 
                  dtype={'A':str},   # Колонку которая имеет заголовок A читает как str 
                  skiprows=2)        # Пропускае тсверзу то кол-во строк которое указать 
df

### read_excel() = чтение excel файла.
Читает Excel-файл (.xlsx, .xls) → DataFrame.

Синтаксис

pd.read_excel(io, sheet_name, header, names, index_col, usecols, dtype, ...)

Основные параметры

Параметр	Что означает	Пример
- io	Путь к файлу	'data.xlsx'
- sheet_name	Имя/номер листа	'Sheet1', 0, None
- header	Строка с заголовками	0
- names	Свои названия	['A', 'B']
- index_col	Колонка-индекс	'id'
- usecols	Какие колонки	'A:C'
- dtype	Типы	{'A': int}
- skiprows	Пропустить строк	5
- nrows	Сколько строк	100

### read_json() =  чтение json файла.
Синтаксис

pd.read_json(path_or_buf, orient, dtype, convert_axes, ...)

Основные параметры :
- Параметр	Что означает	Пример
- path_or_buf	Путь к файлу	'data.json'
- orient	Формат JSON	'records', 'columns', 'index'
- dtype	Типы	{'A': int}
- convert_axes	Преобразовывать оси	True / False
- lines	Читать построчно	True / False

Форматы orient:
- orient	Формат JSON
- 'records'	[{"A": 1, "B": 2}, ...]
- 'columns'	{"A": {"0": 1}, "B": {"0": 2}}
- 'index'	{"0": {"A": 1, "B": 2}}
- 'values'	[[1, 2], [3, 4]]

### read_sql() = чтение из БД.

Читает данные из SQL-базы → DataFrame.

Синтаксис

pd.read_sql(sql, con, index_col, columns, ...)

Основные параметры: 
  Параметр	Что означает	Пример
- sql	SQL-запрос или таблица	"SELECT * FROM users"
- con	Соединение с БД	sqlite3.connect('db.db')
- index_col	Колонка-индекс	'id'
- columns	Колонки	['name', 'age']
- params	Параметры запроса	{'id': 1}

### read_parquet() = чтение Parquet

Читает Parquet-файл (колоночный формат) → DataFrame. Быстрее и меньше CSV.

Синтаксис

pd.read_parquet(path, engine, columns, ...)
Основные параметры
Параметр	Что означает	Пример
path	Путь к файлу	'data.parquet'
engine	Движок	'pyarrow', 'fastparquet'
columns	Какие колонки	['A', 'B']

## Запись данных в разные форматы файлов
df.to_*() — записывает DataFrame → файл.

Методы
- to_csv()  Запись в CSV Записывает DataFrame → CSV-файл.
- to_excel() Запись в excel Записывает в DataFrame → Excel-файл.

### to_csv() = Запись в CSV

Записывает DataFrame → CSV-файл.

Синтаксис

df.to_csv(path_or_buf, sep, index, header, columns, encoding, ...)
Основные параметры
Параметр	Что означает	Пример
- path_or_buf	Путь к файлу	'data.csv'
- sep	Разделитель	',', ';'
- index	Сохранять индекс?	True / False
- header	Сохранять заголовки?	True / False
- columns	Какие колонки	['A', 'B']
- encoding	Кодировка	'utf-8'
- na_rep	Чем заменить NaN	''

In [ ]:

df.to_csv('sandb.csv')

### to_excel() = запись в excel

Записывает DataFrame → Excel-файл.
По умолчанию сохраняет в текущей директории

Синтаксис

df.to_excel(excel_writer, sheet_name, index, header, columns, ...)
Основные параметры
Параметр	Что означает	Пример
- excel_writer	Путь к файлу	'data.xlsx'
- sheet_name	Имя листа	'Sheet1'
- index	Сохранять индекс?	True / False
- header	Заголовки?	True / False
- columns	Какие колонки	['A', 'B']
- startrow	Начальная строка	0
- startcol	Начальная колонка	0

In [ ]:
df = pd.read_csv('E:/python/notebooks/Pandas/sandb.csv')

# сохраняет DataFrame в формате excel в текущей директории, необходимо также указать название  файла 
df.to_excel('sandb_Excel.xlsx')

### to_json() = Запись в JSON

Записывает DataFrame → JSON-файл.

Синтаксис

df.to_json(path_or_buf, orient, date_format, ...)
Основные параметры
- Параметр	Что означает	Пример
- path_or_buf	Путь к файлу	'data.json'
- orient	Формат JSON	'records', 'columns'
- date_format	Формат даты	'iso', 'epoch'
- lines	Построчно?	True / False
- indent	Отступы	2

### to_parquet() = запись в PARQUET

Записывает DataFrame → Parquet-файл. Быстро, компактно.

Синтаксис

df.to_parquet(path, engine, compression, index, ...)
Основные параметры
- Параметр	Что означает	Пример
- path	Путь к файлу	'data.parquet'
- engine	Движок	'pyarrow'
- compression	Сжатие	'snappy', 'gzip'
- index	Сохранять индекс?	True / False
- columns	Какие колонки	['A', 'B'

# Просмотр данных
- df.head()        # как выглядят данные

- df.shape         # сколько строк/колонок

- df.info()        # типы + пропуски

- df.describe()    # статистика

- df.columns       # названия колонок

- df.dtypes        # типы (кратко)

In [ ]:
df = pd.read_excel('E:/python/notebooks/Pandas/sandb_Excel.xlsx')

## Методы

In [ ]:
df = pd.read_excel('E:/python/notebooks/Pandas/sandb_Excel.xlsx')
df

### head()

In [ ]:
# Показывает первые 5 строк по умолчанию. Просто посмотреть, как выглядят данные.
df.head()

In [ ]:
# Показывает первые 2 строк по умолчанию. Просто посмотреть, как выглядят данные.
# df.head(2)

### tail()

In [ ]:
# Показывает последние 5 строк по умолчанию.
df.tail()

In [ ]:
# Показывает последние 3 строк по умолчанию.
df.tail(3)

### info()

In [ ]:
# Показывает структуру: сколько строк, колонок, типы, сколько непустых значений, сколько памяти.
df.info()

### describe()

In [ ]:
# Считает основные статистики для каждой числовой колонки.
df.describe()

## Атрибуты

In [ ]:
df = pd.read_excel('E:/python/notebooks/Pandas/sandb_Excel.xlsx')
df

### shape

In [ ]:
df.shape
# Возвращает кортеж (строки, колонки)

### columns

In [ ]:
# Показывает названия колонок
# Возвращает Index с именами колонок
df.columns

### index

In [ ]:
df.index

### dtypes

In [ ]:
# Показывает какой тип колонок в DataFrame 
# Возвращает тип каждой колонки.
df.dtypes

### values

In [31]:
# данные как NumPy-массив
# Возвращает содержимое DataFrame в виде массива NumPy (без индексов и названий колонок).

df.values
# Особенность: если в DataFrame разные типы (числа + строки), NumPy приведёт всё к общему типу — обычно object. 
# То есть числа могут стать объектами.
# Зачем это нужно: передать данные в NumPy, sklearn, scipy — библиотеки, которые не понимают DataFrame.

array([['Alex', 24.0, 50000.0],
       ['Maria', 25.0, 60000.0],
       [nan, 52.0, nan],
       ['John', nan, 45000.0]], dtype=object)

# Выбор и фильтрация
- При создании DataFrame важно учитывать, что для неё автоматически создаются метки это её инедксы
- Но инедксы мы можем задавать и сами
: = указыват срез откуда до кудова отбирать строк либо колонки
['a':'c'] = отбираем строки с метки a по с тоесть a,b,c
: [:] отбирает все строки 

Если мы задёпм метки сами и мы хотим обратиться по этим меткам то мы можем воспользоватся методом
- df.loc[] — выборка по меткам (label-based)
loc работает с именами индекса и именами столбцов. Верхняя граница включается (в отличие от обычного Python-слайсинга).

## Выбор строк и колонок

### loc[]
по меткам

In [75]:
df = pd.DataFrame({
    'name':['Alice','Bob','Carol','Dave'],
    'age':[30,25,35,28],
    'city':['NY','LA','NY','SF']
}, index = ['a','b','c','d'])
df

    name  age city
a  Alice   30   NY
b    Bob   25   LA
c  Carol   35   NY
d   Dave   28   SF

In [76]:
# Берём из DataFrame строку по метке которой мы сами создали по метке 'b'
# df.loc[строки, столбцы] = синтаксис
df.loc['b'] # Вызов одной строки по метке

name    Bob
age      25
city     LA
Name: b, dtype: object

In [77]:
# Выбираем строки и колонки 
df.loc[['a', 'b'], 
    ['name', 'age']]

    name  age
a  Alice   30
b    Bob   25

In [78]:
df.loc[['a', 'b']]# Вызов двух строк

    name  age city
a  Alice   30   NY
b    Bob   25   LA

In [79]:
df.loc['a':'c'] # Cрез с метками

    name  age city
a  Alice   30   NY
b    Bob   25   LA
c  Carol   35   NY

In [80]:
# Все строки по каким колонкам
df.loc[:,'name':'age']

    name  age
a  Alice   30
b    Bob   25
c  Carol   35
d   Dave   28

In [81]:
# Все колонки и 2 строки
df.loc[['a', 'b'], :]

    name  age city
a  Alice   30   NY
b    Bob   25   LA

### iloc[]
df.iloc[] — выборка по позициям (integer-location)
.iloc работает с числовыми позициями — как обычный Python-список. Верхняя граница НЕ включается.

df.iloc[позиции_строк, позиции_столбцов]

In [84]:
df.loc[0]

KeyError: 0

In [ ]:
df.loc[:]

In [74]:
df.iloc[0:2]

   names  ages
0   Umed    20
1  Numon    30

## at[]

## iat[]

## df[]
df[] — индексация по столбцам и булевой маске
df[...] — «оператор квадратных скобок». Он делает разное в зависимости от того, что внутри.

In [93]:
df[df['age'] > 5]

Empty DataFrame
Columns: [name, age, city]
Index: []

# Группировака и агрегация
Разберём группировку и агрегацию — это одна из самых мощных тем в pandas. Здесь логика такая: разбить → применить → собрать.

In [67]:
df = pd.read_excel('E:/python/notebooks/Pandas/sandb_Excel.xlsx')
df

FileNotFoundError: [Errno 2] No such file or directory: 'E:/python/notebooks/Pandas/sandb_Excel.xlsx'

In [68]:

# Задаём переменные 
names = ['Umed', 'Numon', 'Ali', 'Numon']
ages = [20, 30, 18, 22]

# Присваиваем перменные в качестве занченйи ключей нашего словаря
df = pd.DataFrame({
    'names': names,
    'ages': ages,
})
df

   names  ages
0   Umed    20
1  Numon    30
2    Ali    18
3  Numon    22

In [69]:
# df.groupby() — разбить на группы
# Говорит pandas: сгруппируй строки по значению в колонке.
df.groupby('names')
# Само по себе это ничего не покажет — вернётся объект DataFrameGroupBy, а не таблица. Нужно применить агрегацию.

In [ ]:
# groupby возвращает объект, который можно передат дальше и посчитать агрегированные показатели по всем остальным колонкам
# Например средню по каждой группе 

df.groupby('names').mean()

In [ ]:
# Сумму по каждой группе 
df.groupby('names').sum()
# Зачем: суммарные продажи, общая выручка по региону и т.д.

In [ ]:
# Кол - во сущьностей в каждой группе 
df.groupby('names').count()
# Зачем нужно : сколько записей в каждой группе.  count() не считает NaN — считает только непустые.

In [ ]:
df.groupby('names').min()
# показывает минимальный элемент по каждой группе

In [ ]:
df.groupby('names').max()
# показывает максимальный элемент по каждой группе

In [ ]:
#.agg() — несколько агрегаций сразу
# Это главный метод, когда нужно посчитать несколько функций одновременно или разные функции для разных колонок.
# Необходимо отдельно указывать по какой колонке предстоит считать все показатели в agg()
# Если необходимо посчтать по колонке несколько показателей, то необходиимо сделат это в [] списке
df.groupby('names')['ages'].agg(['mean','min','max','count', 'sum'])

# Обработка пропусков

ЧТО ТАКОЕ ПРОПУСКИ?
Пропуски — это отсутствующие данные в таблице. В pandas они обозначаются как:

NaN (Not a Number) — для чисел

None — для объектов

NaT (Not a Time) — для датv

--isna()	Показывает, где NaN	df.isna()

--notna()	Показывает, где НЕ NaN	df.notna()

--dropna()	Удаляет NaN	df.dropna()

--fillna()	Заполняет NaN	df.fillna(0)

In [20]:
df = pd.DataFrame({
    'name': ['Alex', 'Maria', None, 'John'],
    'age':[24, 25, 52, np.nan],
    'salary':[50000,60000, np.nan, 45000],
})
df

    name   age   salary
0   Alex  24.0  50000.0
1  Maria  25.0  60000.0
2    NaN  52.0      NaN
3   John   NaN  45000.0

## ПОИСК ПРОПУСКОВ

In [21]:
# Метод isna()
# Возвращает True/False для каждой ячейки: True = пропуск, False = есть данные.
df.isna()
# Там где True там None

    name    age  salary
0  False  False   False
1  False  False   False
2   True  False    True
3  False   True   False

In [22]:
# Метод isnull()
# Возвращает True/False для каждой ячейки: True = пропуск, False = есть данные.
df.isnull()
# Там где True там None

    name    age  salary
0  False  False   False
1  False  False   False
2   True  False    True
3  False   True   False

In [23]:
#
df.isnull().sum() # Суммируем кол-во True тоесть пустых строк в каждой колонке

name      1
age       1
salary    1
dtype: int64

In [24]:
# Метод
df.notna()
# Показывает таблицу которая содержит True и False, там где False там пустые значения

    name    age  salary
0   True   True    True
1   True   True    True
2  False   True   False
3   True  False    True

## Удаление замена пропусков

In [25]:
# Метод удаленяи строк содержащих None
df.dropna()
# Все строки таблицы содержащие Nonе будут удалены

    name   age   salary
0   Alex  24.0  50000.0
1  Maria  25.0  60000.0

In [26]:
df.dropna(axis=1)
df

    name   age   salary
0   Alex  24.0  50000.0
1  Maria  25.0  60000.0
2    NaN  52.0      NaN
3   John   NaN  45000.0

In [27]:
# Метод заменяет все пустые строки указаными значениями 
df.fillna(0)
# Параметры 
# value	Чем заполнить	0, 'Unknown', df.mean()
# method	Как заполнить	'ffill' (вперёд), 'bfill' (назад)
# axis	По какой оси	0 (строки), 1 (колонки)
# inplace	Менять ли df	True / False
# limit	Максимум заполнений	1

    name   age   salary
0   Alex  24.0  50000.0
1  Maria  25.0  60000.0
2      0  52.0      0.0
3   John   0.0  45000.0

In [30]:
# РАЗНЫЕ ЗНАЧЕНИЯ ДЛЯ РАЗНЫХ КОЛОНОК
# В указаных колонках занчения Nan поменяются н указанные занчения 
df_filled = df.fillna({
    'name': 'Unknown',
    'age': 0,
    'salary': df['salary'].mean(),
})
df_filled

      name   age        salary
0     Alex  24.0  50000.000000
1    Maria  25.0  60000.000000
2  Unknown  52.0  51666.666667
3     John   0.0  45000.000000

# Объединение

# Сортировка и изменение форма

## Roll Rate

In [ ]:
import pandas as pd
!pip install seaborn
import seaborn as sns


# Long format: одна строка = один кредит × один месяц
df = pd.DataFrame({
    'loan_id':    [100001, 100001, 100001, 100001,
                   100002, 100002, 100002,
                   100003, 100003, 100003],
    'mob':        [1, 2, 3, 4,
                   1, 2, 3,
                   1, 2, 3],
    'dpd_bucket': ['Current', 'Current', '1-30', '31-60',
                   'Current', '1-30', 'Current',
                   '1-30', '31-60', '61-90']
})

print(df)

df = df.sort_values(['loan_id', 'mob']).reset_index(drop=True)


# Текущее состояние (месяц t)
from_state = df[['loan_id', 'mob', 'dpd_bucket']].rename(
    columns={'dpd_bucket': 'from_bucket'}
)

# Следующее состояние (месяц t+1)
to_state = df[['loan_id', 'mob', 'dpd_bucket']].copy()
to_state['mob'] = to_state['mob'] - 1  # сдвигаем на 1 назад
to_state = to_state.rename(columns={'dpd_bucket': 'to_bucket'})

# Объединяем по loan_id и mob
pairs = from_state.merge(to_state, on=['loan_id', 'mob'], how='inner')



print(pairs)


# Упорядочим бакеты
order = ['Current', '1-30', '31-60', '61-90', '90+']

# Строим матрицу переходов
roll_matrix = pd.crosstab(
    pairs['from_bucket'],
    pairs['to_bucket'],
    normalize='index'  # проценты по строкам
) * 100

# Приводим к нужному порядку
roll_matrix = roll_matrix.reindex(index=order, columns=order, fill_value=0)

print(roll_matrix.round(2))

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.heatmap(roll_matrix, annot=True, fmt='.1f', cmap='RdYlGn_r')
plt.xlabel('TO (Куда перешёл)')
plt.ylabel('FROM (Откуда пришёл)')
plt.title('Roll Rate Matrix (%)')
plt.show()