In [1]:
import pandas as pd 
# 1. Чтение и запись данных
# Загрузка из CSV, Excel, JSON, SQL, Parquet и др.
# 2. Структуры данных 
# Series — одномерный массив с метками (как колонка)
#   DataFrame — двумерная таблица (строки × столбцы), главный объект

## DataFrame

In [2]:
# Задача создать табличку с данными 
# Для этого используем словарь
forum_user = {
    'User_ID': [1,2,3,4,5],
    'Username':['umed','namt','numon','amid','help'],
    'Age':[18,42,54,33,None],
    'Joined_Date':pd.to_datetime(['2032-09-02','2032-05-04','2032-06-03','2032-12-10', '2032-11-28']),
    'Total_Post': [150,230,80,420,310],
    'Reputation':[500,760,200,950,500]
}

# Тепер из словаря нужно сделать таблицу для этого есть класс DateFrame из пакета pandas
df = pd.DataFrame(forum_user) # Создаём таблицу и называвем её df
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

In [3]:
df.shape # Форма созданой таблицы

(5, 6)

In [4]:
type(df) # Тип объекта

pandas.DataFrame

In [5]:
df.columns #  Атрибут
# Названия столбцов в формате инедкса

Index(['User_ID', 'Username', 'Age', 'Joined_Date', 'Total_Post',
       'Reputation'],
      dtype='str')

In [6]:
df.columns.tolist()  # Конвертируем индекс в список

['User_ID', 'Username', 'Age', 'Joined_Date', 'Total_Post', 'Reputation']

In [7]:
df.index # Атрибут показывает диапазон индексов
# В нашем случаи у нас индекс начинается с 0 и закансивается с 5 НЕ включительно

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.index.tolist() # конвертируем диапазон индексов в формат списка

[0, 1, 2, 3, 4]

In [9]:
df.dtypes # Смотрим какой тип данных в каждой колонке

User_ID                 int64
Username                  str
Age                   float64
Joined_Date    datetime64[us]
Total_Post              int64
Reputation              int64
dtype: object

In [10]:
df.values # Атрибут .values
# Конкертиуем таблицу в массив numpy (двумерный)

array([[1, 'umed', 18.0, Timestamp('2032-09-02 00:00:00'), 150, 500],
       [2, 'namt', 42.0, Timestamp('2032-05-04 00:00:00'), 230, 760],
       [3, 'numon', 54.0, Timestamp('2032-06-03 00:00:00'), 80, 200],
       [4, 'amid', 33.0, Timestamp('2032-12-10 00:00:00'), 420, 950],
       [5, 'help', nan, Timestamp('2032-11-28 00:00:00'), 310, 500]],
      dtype=object)

In [11]:
df.values[2,1] # Атрибут .values 
# Через values мы можем вызывать любой элемент из таблицы через его индекс
# NumPy-массив двумерный, доступ через [строка, колонка]:

'numon'

In [12]:
df.head() # Метод .head()
# Вызываем первые 5 рядов в таблице
# В качестве аргуемнта метода можно указать число, число строк которое унжно вернуть сверху таблицы

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

In [13]:
df.head(3) # Метод .head()
# В качестве аргуемнта метода можно указать число, число строк которое унжно вернуть сверху таблицы

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200

In [14]:
df.tail() # Метод .ta
# Вызываем последние 5 рядов
# В качестве аргуемнта метода можно указать число, число строк которое унжно вернуть снизу таблицы

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

In [15]:
df.describe() # Метод
# Метод, который считает основные статистики по каждой числовой колонке 
# и возвращает результат в виде нового DataFrame.
# Колонки из строк, дат и объектов не входят в итоговый DataFrame

        User_ID        Age          Joined_Date  Total_Post  Reputation
count  5.000000   4.000000                    5    5.000000    5.000000
mean   3.000000  36.750000  2032-08-27 19:12:00  238.000000  582.000000
min    1.000000  18.000000  2032-05-04 00:00:00   80.000000  200.000000
25%    2.000000  29.250000  2032-06-03 00:00:00  150.000000  500.000000
50%    3.000000  37.500000  2032-09-02 00:00:00  230.000000  500.000000
75%    4.000000  45.000000  2032-11-28 00:00:00  310.000000  760.000000
max    5.000000  54.000000  2032-12-10 00:00:00  420.000000  950.000000
std    1.581139  15.173991                  NaN  133.304163  285.692142

In [16]:
type(df.describe()) # Смотрим тип данных который возвращает метод

pandas.DataFrame

In [17]:
df.describe().index # Через атрибут .index наложеный на метод .descibe(), который показывает инедксы DataFrame 
# который получаем в итоге
# describe() создаёт новую таблицу - Получается новый DataFrame (не тот же df!)
# .index показывает метки этого нового DataFrame

Index(['count', 'mean', 'min', '25%', '50%', '75%', 'max', 'std'], dtype='str')

In [18]:
type(df.describe().index)

pandas.Index

In [19]:
df.describe().round(2) 
# Цепочка методов. 
# Метод .describe() принимает объект df и выводит новый объект DataFrame
# Далее по цепочке идёт другой метод .round(), который принимает новый объект DataFrame 
# и округляет до 2 знаков после запятой

       User_ID    Age          Joined_Date  Total_Post  Reputation
count     5.00   4.00                    5         5.0        5.00
mean      3.00  36.75  2032-08-27 19:12:00       238.0      582.00
min       1.00  18.00  2032-05-04 00:00:00        80.0      200.00
25%       2.00  29.25  2032-06-03 00:00:00       150.0      500.00
50%       3.00  37.50  2032-09-02 00:00:00       230.0      500.00
75%       4.00  45.00  2032-11-28 00:00:00       310.0      760.00
max       5.00  54.00  2032-12-10 00:00:00       420.0      950.00
std       1.58  15.17                  NaN       133.3      285.69

In [20]:
df.select_dtypes(include='int64') # метод select_dtypes
# метод показывает те колонк которые соответсвуют с тимоп данных который мы сами указали

   User_ID  Total_Post  Reputation
0        1         150         500
1        2         230         760
2        3          80         200
3        4         420         950
4        5         310         500

In [21]:
df.select_dtypes(include='str') # получаем только те колонки которые имеют тип данных str

  Username
0     umed
1     namt
2    numon
3     amid
4     help

In [22]:
df.select_dtypes(include='object')  # получаем только те колонки которые имеют тип данных str

C:\Users\umed\AppData\Local\Temp\ipykernel_11976\2158412411.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object')  # получаем только те колонки которые имеют тип данных str

  Username
0     umed
1     namt
2    numon
3     amid
4     help

In [23]:
df.isna() # Метод .isna() (is not avalible)
# Метод указывает на  те ячейки которые пустые либо содерждать None
# Выводом будет таблица где будет показана ячейка которая будет содержать true
# и это ячейка будет содержать None

   User_ID  Username    Age  Joined_Date  Total_Post  Reputation
0    False     False  False        False       False       False
1    False     False  False        False       False       False
2    False     False  False        False       False       False
3    False     False  False        False       False       False
4    False     False   True        False       False       False

In [24]:
df.isna().sum() # Суммируем колво пустых ячеек либо содержащих None

User_ID        0
Username       0
Age            1
Joined_Date    0
Total_Post     0
Reputation     0
dtype: int64

In [25]:
df.select_dtypes(include='int64').sum()

User_ID         15
Total_Post    1190
Reputation    2910
dtype: int64

In [26]:
df.columns

Index(['User_ID', 'Username', 'Age', 'Joined_Date', 'Total_Post',
       'Reputation'],
      dtype='str')

## Serias

In [27]:
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

In [28]:
df['User_ID']

0    1
1    2
2    3
3    4
4    5
Name: User_ID, dtype: int64

In [29]:
type(df['User_ID'])

pandas.Series

In [30]:
user_nameserias = df['Username']
user_nameserias

0     umed
1     namt
2    numon
3     amid
4     help
Name: Username, dtype: str

In [31]:
type(user_nameserias) # Тип данных Serias

pandas.Series

In [32]:
user_nameserias.values

<StringArray>
['umed', 'namt', 'numon', 'amid', 'help']
Length: 5, dtype: str

In [33]:
type(user_nameserias.values)

pandas.arrays.StringArray

In [34]:
df['Username'].value_counts() # метод value_counts()
# метод показывает сколько  одинаковых значенйи повторяются в одной колонке

Username
umed     1
namt     1
numon    1
amid     1
help     1
Name: count, dtype: int64

In [35]:
df['Reputation'].value_counts() 
# сортировка будет по возрастанию от маленького к большому

Reputation
500    2
760    1
200    1
950    1
Name: count, dtype: int64

In [36]:
df['Reputation'].value_counts(ascending=True)
# сортировка будет по убыванию от большого к маленькому

Reputation
760    1
200    1
950    1
500    2
Name: count, dtype: int64

In [37]:
user_nameserias.count() #  считаем кол-во

np.int64(5)

In [38]:
df['Reputation'].unique() # Метод unique
# Метод показывает уникальне значения колонки

array([500, 760, 200, 950])

In [ ]:
df['Reputation'].