In [1]:
import pandas as pd
import numpy as np

In [2]:
# Задача создать табличку с данными 
# Для этого используем словарь
forum_user = {
    'User_ID': [1,2,3,4,5],
    'Username':['umed','namt','numon','amid','help'],
    'Age':[18,42,54,33,None],
    'Joined_Date':pd.to_datetime(['2032-09-02','2032-05-04','2032-06-03','2032-12-10', '2032-11-28']),
    'Total_Post': [150,230,80,420,310],
    'Reputation':[500,760,200,950,500]
}

# Тепер из словаря нужно сделать таблицу для этого есть класс DateFrame из пакета pandas
df = pd.DataFrame(forum_user) # Создаём таблицу и называвем её df
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

## Filtering

In [3]:
df[['Username', 'Age']] # В [] в квадратных скобках указываем через запятую колонки
# Выборочно берём только те колонк иокторые нам необходимы

  Username   Age
0     umed  18.0
1     namt  42.0
2    numon  54.0
3     amid  33.0
4     help   NaN

In [4]:
df.loc[3]

User_ID                          4
Username                      amid
Age                           33.0
Joined_Date    2032-12-10 00:00:00
Total_Post                     420
Reputation                     950
Name: 3, dtype: object

In [5]:
type(df.loc[3])

pandas.Series

In [6]:
df.loc[2:3] # отбираем те строки которые с индекса 2 ао 3 включительно
# Возвращает DataFrame , точнеестроки с индексом 2 и 3

   User_ID Username   Age Joined_Date  Total_Post  Reputation
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950

In [7]:
df.loc[2:3, ['Username', 'Joined_Date', 'Reputation']]

  Username Joined_Date  Reputation
2    numon  2032-06-03         200
3     amid  2032-12-10         950

In [8]:
df.iloc[3]

User_ID                          4
Username                      amid
Age                           33.0
Joined_Date    2032-12-10 00:00:00
Total_Post                     420
Reputation                     950
Name: 3, dtype: object

In [9]:
df.iloc[2:4]

   User_ID Username   Age Joined_Date  Total_Post  Reputation
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950

In [10]:
df.iloc[2:4, 1:4]

  Username   Age Joined_Date
2    numon  54.0  2032-06-03
3     amid  33.0  2032-12-10

### Filter

In [11]:
df['Age']>= 25 
# Получаем серию в которая значения тех строк которые боьше либо равны 25 будут становиться True

0    False
1     True
2     True
3     True
4    False
Name: Age, dtype: bool

In [12]:
# Пример фильтрации по строкам
df[df['Age'] >= 25] # Конвертируем серию в DataFrame
# все строки которые не убовлетворяют условие не будт оотображены в итоговой таблицу

   User_ID Username   Age Joined_Date  Total_Post  Reputation
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950

In [13]:
df[df['Total_Post']>= 200]

   User_ID Username   Age Joined_Date  Total_Post  Reputation
1        2     namt  42.0  2032-05-04         230         760
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

### Операторы & и | двойные условия

In [14]:
# оператор и &
# Сначала применяестя фильтрация по одной колонке потом по второй колонке 
# После фильтрации убираются строки по обоим колонкам и выводится конечная таблица 
df[(df['Age']>=25) & (df['Total_Post']>= 100)] # Двйоноеусловие срабатывает только в случаи использования оператора и &
# Двоное условие

   User_ID Username   Age Joined_Date  Total_Post  Reputation
1        2     namt  42.0  2032-05-04         230         760
3        4     amid  33.0  2032-12-10         420         950

In [15]:
# оператор и |
df[(df['Age']>=25) | (df['Total_Post']>= 100)]

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

In [16]:
# бёрм те строки из колонки которые равны определёному значению
df['Reputation'].isin([200,500]) # метод .isin() оставляет только те строки

0     True
1    False
2     True
3    False
4     True
Name: Reputation, dtype: bool

### isin() and range(), date_range()

In [17]:
df[df['Reputation'].isin([200,500])] # метод .isin()
# Метод отбирает тошльок те строки из колонки которые равны 200 либо 500

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
2        3    numon  54.0  2032-06-03          80         200
4        5     help   NaN  2032-11-28         310         500

In [18]:
df[df['Reputation'].isin(range(200, 500))] 
# берутся только те строки из колонки которые начинаются с 200 и заканчиваются на 400

   User_ID Username   Age Joined_Date  Total_Post  Reputation
2        3    numon  54.0  2032-06-03          80         200

In [19]:
date_range =pd.date_range(start='2032-03-01', end='2032-08-01')
date_range

DatetimeIndex(['2032-03-01', '2032-03-02', '2032-03-03', '2032-03-04',
               '2032-03-05', '2032-03-06', '2032-03-07', '2032-03-08',
               '2032-03-09', '2032-03-10',
               ...
               '2032-07-23', '2032-07-24', '2032-07-25', '2032-07-26',
               '2032-07-27', '2032-07-28', '2032-07-29', '2032-07-30',
               '2032-07-31', '2032-08-01'],
              dtype='datetime64[us]', length=154, freq='D')

In [20]:
df[df['Joined_Date'].isin(date_range)] 
# отбираем те строки из колонки занчение которыч равны в диапазоне указаных дат

   User_ID Username   Age Joined_Date  Total_Post  Reputation
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200

In [21]:
df[df['Joined_Date'].isin(pd.date_range(start='2032-03-01', end='2032-08-01'))]

   User_ID Username   Age Joined_Date  Total_Post  Reputation
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200

## Sorting

In [24]:
df.sort_values(by='User_ID', ascending=True) # метод сортирует по возрастанию
# Метод фиьтрует по колонке Age по возрастанию
# Сортировка по колонке

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

In [23]:
# Сортировка по строке
df[['Age', 'Total_Post', 'Reputation']].sort_values(by=2, axis=1 ,ascending=False)
# b=2 соритровка по инедксу 2 
# axis=1 сортировка по колонкам 
# ascending=False сортировка по убыванию

   Reputation  Total_Post   Age
0         500         150  18.0
1         760         230  42.0
2         200          80  54.0
3         950         420  33.0
4         500         310   NaN