In [1]:
import pandas as pd
import numpy as np

In [2]:
# Задача создать табличку с данными 
# Для этого используем словарь
forum_user = {
    'User_ID': [1,2,3,4,5],
    'Username':['umed','namt','numon','amid','help'],
    'Age':[18,42,54,33,None],
    'Joined_Date':pd.to_datetime(['2032-09-02','2032-05-04','2032-06-03','2032-12-10', '2032-11-28']),
    'Total_Post': [150,230,80,420,310],
    'Reputation':[500,760,200,950,500]
}

# Тепер из словаря нужно сделать таблицу для этого есть класс DateFrame из пакета pandas
df = pd.DataFrame(forum_user) # Создаём таблицу и называвем её df
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation
0        1     umed  18.0  2032-09-02         150         500
1        2     namt  42.0  2032-05-04         230         760
2        3    numon  54.0  2032-06-03          80         200
3        4     amid  33.0  2032-12-10         420         950
4        5     help   NaN  2032-11-28         310         500

##  Добавление строк и колонок в таблицу

In [3]:
# Добавляем новую колонку
df['Language'] = 'English'
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation Language
0        1     umed  18.0  2032-09-02         150         500  English
1        2     namt  42.0  2032-05-04         230         760  English
2        3    numon  54.0  2032-06-03          80         200  English
3        4     amid  33.0  2032-12-10         420         950  English
4        5     help   NaN  2032-11-28         310         500  English

In [4]:
# Перезаписываем значения сущесвующей колонки (всех строк колонки)
df['Reputation'] = 100
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation Language
0        1     umed  18.0  2032-09-02         150         100  English
1        2     namt  42.0  2032-05-04         230         100  English
2        3    numon  54.0  2032-06-03          80         100  English
3        4     amid  33.0  2032-12-10         420         100  English
4        5     help   NaN  2032-11-28         310         100  English

In [5]:
# Перезаписываем данные колонки по каждой строке
df['Reputation'] = [100,200,300,150,50]
# Кол-во задаваемых строк должно быть равно кол-ву 
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation Language
0        1     umed  18.0  2032-09-02         150         100  English
1        2     namt  42.0  2032-05-04         230         200  English
2        3    numon  54.0  2032-06-03          80         300  English
3        4     amid  33.0  2032-12-10         420         150  English
4        5     help   NaN  2032-11-28         310          50  English

In [6]:
# Добоавляем новую колонку и в новой колонке вставляем значеняи по каждой строке
df['Active']= [True,False,False,False,True]
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation Language  Active
0        1     umed  18.0  2032-09-02         150         100  English    True
1        2     namt  42.0  2032-05-04         230         200  English   False
2        3    numon  54.0  2032-06-03          80         300  English   False
3        4     amid  33.0  2032-12-10         420         150  English   False
4        5     help   NaN  2032-11-28         310          50  English    True

In [7]:
a = df['Age'].values
a

array([18., 42., 54., 33., nan])

In [8]:
c = df['Reputation'].values
c

array([100, 200, 300, 150,  50])

In [9]:
g = a + c
g

array([118., 242., 354., 183.,  nan])

In [10]:
c.sum()

np.int64(800)

## Merge слияние Таблиц

In [11]:
total_comments = {
    'Total_Comments': [20,30,40,50,60,70]
}


df2 = pd.DataFrame(total_comments)
df2

   Total_Comments
0              20
1              30
2              40
3              50
4              60
5              70

In [12]:
pd.concat([df, df2]) # метод concat([]) слияние 2 таблиц
# По умолячанию слоияние происходит по оси 0

,User_ID,Username,Age,Joined_Date,Total_Post,Reputation,Language,Active,Total_Comments
0,1.0,umed,18.0,2032-09-02,150.0,100.0,English,True,NaN
1,2.0,namt,42.0,2032-05-04,230.0,200.0,English,False,NaN
2,3.0,numon,54.0,2032-06-03,80.0,300.0,English,False,NaN
3,4.0,amid,33.0,2032-12-10,420.0,150.0,English,False,NaN
4,5.0,help,NaN,2032-11-28,310.0,50.0,English,True,NaN
0,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,20.0
1,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,30.0
2,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,40.0
3,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,50.0
4,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,60.0
5,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,70.0

In [13]:
df3 = pd.concat([df, df2], axis=1)
# Указываем сами по какой оси слиять (по ои axis=1)
# Добавялется новая колонка 
df3

,User_ID,Username,Age,Joined_Date,Total_Post,Reputation,Language,Active,Total_Comments
0,1.0,umed,18.0,2032-09-02,150.0,100.0,English,True,20
1,2.0,namt,42.0,2032-05-04,230.0,200.0,English,False,30
2,3.0,numon,54.0,2032-06-03,80.0,300.0,English,False,40
3,4.0,amid,33.0,2032-12-10,420.0,150.0,English,False,50
4,5.0,help,NaN,2032-11-28,310.0,50.0,English,True,60
5,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,70

## .drop Удаление колонок либо строк

### Удаление колонок

In [14]:
# df.drop(['Language']) 
# По умолчанию метод удаляет по оси 0 axis=0 тоесть по строкам, а мы указываем колонку, 
# поэтому необходимо менят ось на 1

In [15]:
df.drop(['Language'], axis=1)
# Оригинальная табличка не меняется для этого небхо

   User_ID Username   Age Joined_Date  Total_Post  Reputation  Active
0        1     umed  18.0  2032-09-02         150         100    True
1        2     namt  42.0  2032-05-04         230         200   False
2        3    numon  54.0  2032-06-03          80         300   False
3        4     amid  33.0  2032-12-10         420         150   False
4        5     help   NaN  2032-11-28         310          50    True

In [16]:
df #оригинальная таблица при этом не меняется для его изменения необходимо указать параметр inplace=True

   User_ID Username   Age Joined_Date  Total_Post  Reputation Language  Active
0        1     umed  18.0  2032-09-02         150         100  English    True
1        2     namt  42.0  2032-05-04         230         200  English   False
2        3    numon  54.0  2032-06-03          80         300  English   False
3        4     amid  33.0  2032-12-10         420         150  English   False
4        5     help   NaN  2032-11-28         310          50  English    True

In [17]:
df.drop(['Language'], axis=1, inplace=True)
# Теперь оригинальная таблица изменилась, колонка Lаnguage удалилась 
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation  Active
0        1     umed  18.0  2032-09-02         150         100    True
1        2     namt  42.0  2032-05-04         230         200   False
2        3    numon  54.0  2032-06-03          80         300   False
3        4     amid  33.0  2032-12-10         420         150   False
4        5     help   NaN  2032-11-28         310          50    True

In [18]:
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation  Active
0        1     umed  18.0  2032-09-02         150         100    True
1        2     namt  42.0  2032-05-04         230         200   False
2        3    numon  54.0  2032-06-03          80         300   False
3        4     amid  33.0  2032-12-10         420         150   False
4        5     help   NaN  2032-11-28         310          50    True

### Удаление строк

In [29]:
#df.drop([2, 3], inplace=True) # Метод удалил строки по индексу 2 и 3 включительно 
df

   User_ID Username   Age Joined_Date  Total_Post  Reputation  Active
0        1     umed  18.0  2032-09-02         150         100    True
1        2     namt  42.0  2032-05-04         230         200   False
4        5     help   NaN  2032-11-28         310          50    True